### PR TITLE
Add support for XEP-0308

### LINKED ISSUE #278: XEP-0308 (Last Message Correction) support
[XEP-0308 (Last Message Correction)](https://xmpp.org/extensions/xep-0308.html) would be a nice XEP to be supported.

Maybe an `aioxmpp.Message.edited` boolean for when an incoming message is an edit of an already existing one?

### PR DESCRIPTION
**Pull request by LukeMarlin**
Closes #278

### CODE REVIEW

**Comment by LukeMarlin** [comment]
Here we go @horazont . I've based it on the code your mentioned and took misc.delay as an example for the rest. I also took the liberty to add two missing spaces. I had no idea if I was to change version but hey, that's a draft anyway.

Feel free to tell me if something more or different is needed.

PS: Sorry about the force push, it was just a wrong file name in the license header.

**Comment by LukeMarlin** [comment]
Quick test tool:

    import aioxmpp
    from aioxmpp.misc import Replace
    jid = aioxmpp.JID.fromstr("jid1@jid.jid")
    recipient = aioxmpp.JID.fromstr("jid2@jid.jid")
    msg = aioxmpp.Message(to=recipient, type_=aioxmpp.MessageType.CHAT)
    msg.body[None] = "Message with a tipo"
    client = aioxmpp.PresenceManagedClient(jid, aioxmpp.make_security_layer("password"))
    async with client.connected() as stream:
        await client.send(msg)
        msg2 = aioxmpp.Message(to=recipient, type_=aioxmpp.MessageType.CHAT)
        msg2.xep0308_replace = Replace()
        msg2.body[None] = "Message without a typo"
        input("Do you want to correct the message '" + msg.id_ + "'")
        msg2.xep0308_replace.id_ = msg.id_
        await client.send(msg2)`

**Comment by horazont** [comment]
How the heck did I overlook this PR?

**Comment by horazont** [comment]
@LukeMarlin Thank you very much and sorry for the insane delay. I must’ve missed the github notification email for some reason.

Can you please add the newly added XSO stuff to the misc/__init__.py docstring, like the other ones which are integrated?

**Comment by horazont** [comment]
You know what, since I’ve let you wait for that long, I’m going to do that myself!

**Comment by LukeMarlin** [comment]
Completely forgot about it as well but hey, better late than never! Thanks for looking at it :)

**Pull request merged**
