### PR TITLE
Add support for XEP-0009

### PR DESCRIPTION
**Pull request by NikoConn**

### CODE REVIEW

**Comment by javipalanca** [comment]
Hi @horazont 
I hope you will be interested in this XEP and consider it to be added to aioxmpp. It has been developed by my collaborator @NikoConn as part of his master work.
If you need something to be fixed or adapted just tell us.

**Comment by horazont** [comment]
Wow, that's looking pretty great on first glance!

I'll look into it in a week or so, I've got a lot of other things going on right now!

**Comment by horazont** [comment]
Maybe one thing which is already worth mentioning: I try to stick to https://cbea.ms/git-commit/. Please try to rework your commit history to adhere to this pattern.

As this is adding a new feature, squashing everything to a single commit is generally ok.

**Comment by javipalanca** [comment]
Hi @horazont,
Would you please provide a comment if you think you will be able to analyze this pull request soon? It would be very useful for us to have it integrated to start using it in our platform. Thank you!
Of course, if more fixes are needed just tell us.

**Comment by horazont** [comment]
@javipalanca Ohhhh this totally slipped through the cracks. I'll take a look by the end of the year! Thanks for the reminder!

**Comment by javipalanca** [comment]
Just a kind reminder :)

**Comment by horazont** [comment]
Hi @javipalanca, @NikoConn and sorry for the delay. 

Thank you alot for your contribution.

I had to wrestle with the CI a bit and hunt down a really obscure Python 3.9-and-earlier error (if you dare, check out the long comment in the unit tests of #383...).

This is looking pretty great already. The only thing I'd like to have added is a bunch of documentation things:

- Add `rpc` to Protocol part and XEP implementations in `docs/api/public/index.rst`
- Add XEP-0009 to the list of supported XEPs in the `docs/index.rst`
- Add a changelog notice for Version 0.14 (make a new heading) in `docs/api/changelog.rst`. Please add any attribution to yourself as you like!

Please also rebase on current `devel`, so that the CI may run successfully.

**Comment by NikoConn** [comment]
Hi @horazont. Thank you a lot for your comments. Just pushed the things you said :wink:

**Comment by horazont** [comment]
@NikoConn Thanks for the contribution!

**Pull request merged**
